name: Publish Python 🐍 distributions 📦 to PyPI
on:
  pull_request:
  release:
    types: [published]
defaults:
  run:
    shell:
      bash
jobs:
  build-sdist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Verify tag matches version
        run: |
          set -ex
          version=$(cat TTS/VERSION)
          tag="${GITHUB_REF/refs\/tags\/}"
          if [[ "v$version" != "v$version" ]]; then
            exit 1
          fi
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install -U pip setuptools wheel build
      - run: |
          python -m build
      - run: |
          pip install dist/*.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz
  build-wheels:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install -U pip setuptools wheel build
      # - name: Build manylinux Python wheels
      #   uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
      #   with:
      #     python-versions: 'cp37-cp37m'
      - run:
          python -m pip install -r requirements.txt
      - run:
          python setup.py bdist_wheel --plat-name=manylinux1_x86_64
      - run: |
          python -m pip install dist/*-manylinux*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*-manylinux*.whl
  publish-artifacts:
    runs-on: ubuntu-20.04
    needs: [build-sdist, build-wheels]
    steps:
      - run: |
          mkdir dist
      - uses: actions/download-artifact@v2
        with:
          name: "sdist"
          path: "dist/"
      - uses: actions/download-artifact@v2
        with:
          name: "wheel-3.7"
          path: "dist/"
      - run: |
          ls -lh dist/
